# Generated by Django 5.0.2 on 2024-02-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_DB',
            fields=[
                ('bookno', models.IntegerField(primary_key='bookno', serialize=False)),
                ('bookname', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=30)),
                ('pageno', models.DateField()),
                ('language', models.IntegerField()),
            ],
        ),
    ]
